//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRestful
{
    using Services;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class UsersEntities : DbContext, IUserEntitiesContext
    {
        public UsersEntities()
            : base("name=UsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public void MarkAsModified(User item)
        {
            Entry(item).State = EntityState.Modified;
        }

       
        public virtual DbSet<User> Users { get; set; }
    }
}
